#!/bin/bash
rm -rf build
mkdir build
git worktree prune
rm -rf .git/worktrees/build/
git worktree add -B gh-pages build origin/gh-pages
npm run build
cd build && git add --all && git commit -m "Publishing to gh-pages" && cd ..
git push origin gh-pages --force